### ISSUE TITLE
Licensing matters

### ISSUE THREAD

**Issue by idlesign** [mfvanek/pg-index-health-sql#1]
Hi,

You've sourced it under GPL which effectively prevents other libraries from using it under anything rather than GPL. That can lead to distibution problems. 
I'd like to use those SQLs in BSD licensed project.

Is it possible to double license those SQLs, or maybe switch altogether to a more permissive license?

**Comment by mfvanek** [comment]
Hi Igor,
I've re-licensed all sql queries under Apache License 2.0. Hope it solves all troubles.

**Comment by idlesign** [comment]
Thank you!
