### ISSUE TITLE
Slowest query inspection

### ISSUE THREAD

**Issue by idlesign** [mfvanek/pg-index-health-sql#2]
Maybe add something like

```
SELECT (total_time / 1000 / 60) as total, (total_time / calls) as avg, query
FROM pg_stat_statements
ORDER BY 1 DESC
LIMIT 5;
```
to get stats on query perfomance. It's seems to be partly related to index health.

**Comment by mfvanek** [comment]
**pg_stat_statements** is not a part of a standard PostgreSQL distribution. It's an extension without which given query will fail. That's why I don't want to add sql queries which rely on extensions.

I'll think about ext folder for such queries.

**Comment by idlesign** [comment]
Yes, we can either separate those files or IF EXISTS in places where it's applicable.
