### ISSUE TITLE
ERROR...

### ISSUE THREAD

**Issue by Nikita1909** [mfvanek/pg-index-health-sql#22]
Здравствуйте, подскажите пожалуйста, что означает эта строка? 
Она присутствует в каждом коде проверки.
    `WHERE pn.nspname = :schema_name_param::text`
Работаю через pgAdmin, и при наличии этой строки, выдает ошибку:
"ERROR:  syntax error at or near ":"
LINE 13:     psai.schemaname = :schema_name_param::text and"

Без этой строки, всё работает, но возможно не корректно.

**Comment by Nikita1909** [comment]
`where bloat_percentage >= :bloat_percentage_threshold::integer`
Снова 
`ERROR:  syntax error at or near ":"
LINE 140: where bloat_percentage >= :bloat_percentage_threshold::integ...`

**Comment by mfvanek** [comment]
@Nikita1909 
This is a Java-style named parameter used to filter out data belonging to particular schema.
See also https://stackoverflow.com/questions/1097855/using-a-variable-instead-of-a-parameter-index-with-a-jdbc-prepared-statement

You can replace it with your own schema name. For example
`psai.schemaname = 'public'::text`

**Comment by idlesign** [comment]
@Nikita1909 

> Без этой строки, всё работает, но возможно не корректно.

Для информации. Используемая нотация, например, нарочно совместима с DataGrip (и прочими IDE на базе Idea от JetBrains): то есть, если поместить SQL с такой нотацией в Query Console, то при попытке запуска будет выведено диалоговое окно для ввода параметров (в вашем примере в диалоге будет поле ввода для `schema_name_param`).

FYI. The notation, for example, is deliberately compatible with DataGrip (and other Idea-based IDEs from JetBrains): i.e. if you try to execute this SQL in a Query Console a dialog will pop up to help you to fill in the params (for you very case, `schema_name_param` input will present itself in the dialog).
